server:
  port: 8085

spring:
  application:
    name: pdm-floating-population
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/pdm_shard_3?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      timeout: 3000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 3000ms
  elasticsearch:
    uris: http://127.0.0.1:9200
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: pdm

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: YTk5ZjY3ZDIxMzQ1NmY4OTBiMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6
